import { prisma } from './prisma';

const WEEKLY_SCHEDULE = [
  { dayOfWeek: 1, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 1, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 1, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 1, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 1, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 1, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 1, startTime: '14:00', endTime: '16:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 1, startTime: '16:00', endTime: '16:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 1, startTime: '16:30', endTime: '18:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 1, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 1, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 2, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 2, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 2, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 2, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 2, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 2, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 2, startTime: '14:00', endTime: '17:00', category: 'class', label: 'Clase' },
  { dayOfWeek: 2, startTime: '17:00', endTime: '18:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 2, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 2, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 3, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 3, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 3, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 3, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 3, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 3, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 3, startTime: '14:00', endTime: '16:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 3, startTime: '16:00', endTime: '18:00', category: 'class', label: 'Clase' },
  { dayOfWeek: 3, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 3, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 4, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 4, startTime: '14:00', endTime: '16:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '16:00', endTime: '16:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 4, startTime: '16:30', endTime: '18:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 4, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 4, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 5, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 5, startTime: '14:00', endTime: '16:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '16:00', endTime: '16:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 5, startTime: '16:30', endTime: '18:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 5, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 5, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 6, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 6, startTime: '14:00', endTime: '16:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '16:00', endTime: '16:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 6, startTime: '16:30', endTime: '18:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 6, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 6, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '08:00', endTime: '09:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '09:00', endTime: '10:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '10:00', endTime: '11:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '11:00', endTime: '11:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 0, startTime: '11:30', endTime: '13:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '13:00', endTime: '14:00', category: 'comida', label: 'Almuerzo' },
  { dayOfWeek: 0, startTime: '14:00', endTime: '16:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '16:00', endTime: '16:30', category: 'ocio', label: 'Descanso' },
  { dayOfWeek: 0, startTime: '16:30', endTime: '18:00', category: 'work', label: 'Trabajo' },
  { dayOfWeek: 0, startTime: '18:00', endTime: '20:00', category: 'ocio', label: 'Cena + Ocio' },
  { dayOfWeek: 0, startTime: '20:00', endTime: '23:00', category: 'work', label: 'Trabajo' },
];

export async function seedScheduleForUser(userId: string) {
  const existing = await prisma.scheduleBlock.count({ where: { userId } });
  if (existing > 0) return;

  await prisma.scheduleBlock.createMany({
    data: WEEKLY_SCHEDULE.map((block) => ({
      userId,
      dayOfWeek: block.dayOfWeek,
      startTime: block.startTime,
      endTime: block.endTime,
      category: block.category,
      label: block.label,
    })),
  });
}
